version: "3.7"

services:
  mongodb:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: admin_pass
      MONGO_INITDB_DATABASE: my_database
    volumes:
      - ./db-data:/data/db
      - ./backup:/backup
    ports:
      - 28017:27017
